services:
  - type: web
    name: pgweb-console
    env: docker
    image: sosedoff/pgweb
    plan: free
    autoDeploy: false
    envVars:
      - key: DATABASE_URL
        value: postgres://boonjun:xiOe63X4iaczwTAcNfUYwS8oWrDExkHX@dpg-d11rb03uibrs73eh87vg-a:5432/render_4m
