services:
  - type: web
    name: pgweb
    env: docker
    plan: free
    repo: <boonjun123654/TTR>
    branch: main
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: 4M
          property: connectionString
